# Site settings
title: 302 Found
email: blixa@projectmakeit.com
description: > # this means to ignore newlines until "baseurl:"
  Personal site of Blixa Morgan, aka MrMakeIt.  Contains projects, rants, and 
  other things that may or may not be from other cool sites around the net.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.mrmakeit.me" # the base hostname & protocol for your site
twitter_username: blixam
github_username:  mrmakeit
google_plus: +BlixaMorgan
google_username: Blixa Morgan
# Build settings
markdown: kramdown
